### PR TITLE
Fix .NET SDK 8 compatibility

### LINKED ISSUE #746: Error building using .NET SDK 8 due to Roslyn version incompatibility
CSnakes Version: 1.2.1
.NET 8 sdk version 8.0.416

Console project dotnet build gives error:
`CSC : error CS9057: The analyzer assembly \.nuget\packages\csnakes.runtime\1.2.1\analyzers\dotnet\cs\CSnakes.SourceGeneration.dll' references vers ion '4.12.0.0' of the compiler, which is newer than the currently running version '4.11.0.0'.`

Works on version 1.0.35 of CSnakes

### PR DESCRIPTION
**Pull request by atifaziz**
This PR fixes #746.

- It introduces a new workflow for .NET SDK compatibility testing and adds a sample application to verify cross-version compatibility of the `CSnakes.Runtime` package. The workflow builds and tests the package against multiple .NET SDK versions, and includes configuration and sample code for the compatibility test.
- It downgrades `Microsoft.CodeAnalysis.Analyzers` and `Microsoft.CodeAnalysis.CSharp` to versions that allow users to build their projects with .NET SDK 8.
- It detects the C# language version of the project and avoids binding to the obsolete overload `PyObject.Call(params PyObject[])` when the language version is C# 12. It makes sure that the `PyObject.Call(params ReadOnlySpan<PyObject>)` overload is bound in all cases by changing the generated code. A test is also added to exercise this path.

### CODE REVIEW

File: .github/workflows/sdk-compat.yml [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+      - uses: actions/checkout@v4
+        with:
+          submodules: 'true'
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+
+      - name: Pack NuGet packages
+        run: dotnet pack --tl:off -c Release -p:VersionSuffix='alpha.${{ github.run_number }}' -bl:pack.binlog src
+
```
[the remark this answers is not in the document]
Comment (atifaziz) [reply .github/workflows/sdk-compat.yml]: I thought we had a `global.json`, but I was wrong. Done with 6263e84609e31c243fd13b6ab65ea4cc03046ab6.

File: .github/workflows/sdk-compat/TestApp.csproj [hunk 2]
```diff
@@ -0,0 +1,13 @@
+<Project Sdk="Microsoft.NET.Sdk">
+
+  <PropertyGroup>
+    <OutputType>Exe</OutputType>
+    <TargetFramework>net8.0</TargetFramework>
+    <Nullable>enable</Nullable>
+  </PropertyGroup>
+
+  <ItemGroup>
+    <PackageReference Include="CSnakes.Runtime" Version="*-*" />
```
[the remark this answers is not in the document]
Comment (atifaziz) [reply .github/workflows/sdk-compat/TestApp.csproj]: @copilot it seems to work just fine and intentional. The version doesn't matter at all since the package feed is expected to pick the one and only packed.

File: .github/workflows/sdk-compat.yml [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+        with:
+          submodules: 'true'
+
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v4
+        with:
+          dotnet-version: '9.0.x'
+
+      - name: Pack NuGet packages
+        run: dotnet pack --tl:off -c Release -p:VersionSuffix='alpha.${{ github.run_number }}' -bl:pack.binlog src
```
[the remark this answers is not in the document]
Comment (atifaziz) [reply .github/workflows/sdk-compat.yml]: This is not an issue since `src` is expected to contain a solution and will pack precisely the projects that can be packed.
