### ISSUE TITLE
Error building using .NET SDK 8 due to Roslyn version incompatibility

### ISSUE THREAD

**Issue by cricketts497** [tonybaloney/CSnakes#746]
CSnakes Version: 1.2.1
.NET 8 sdk version 8.0.416

Console project dotnet build gives error:
`CSC : error CS9057: The analyzer assembly \.nuget\packages\csnakes.runtime\1.2.1\analyzers\dotnet\cs\CSnakes.SourceGeneration.dll' references vers ion '4.12.0.0' of the compiler, which is newer than the currently running version '4.11.0.0'.`

Works on version 1.0.35 of CSnakes
